import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { getPaySlipsByEmployee } from '../../services/api';
import { DollarSign, TrendingUp, TrendingDown, AlertTriangle, CheckCircle } from 'lucide-react';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function MyPayslips() {
  const { user } = useAuth();
  const [payslips, setPayslips] = useState([]);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    getPaySlipsByEmployee(user?.employeeId)
      .then(r => { setPayslips(r.data); if (r.data.length) setSelected(r.data[0]); })
      .catch(() => {});
  }, [user]);

  return (
    <div>
      <div className="mb-8 animate-fade-up">
        <p className="text-xs font-mono text-muted uppercase tracking-widest mb-1">My Finance</p>
        <h1 className="font-display font-bold text-3xl text-bright tracking-tight">Pay Slips</h1>
      </div>

      {payslips.length === 0 ? (
        <div className="stat-card text-center py-16 animate-fade-up">
          <DollarSign size={32} className="text-muted mx-auto mb-3"/>
          <p className="text-dim font-body">No payslips available yet</p>
          <p className="text-muted font-mono text-xs mt-1">Payslips are generated by HR each month</p>
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-6 animate-fade-up delay-100">
          {/* List */}
          <div className="col-span-1 space-y-2">
            <p className="text-xs font-mono text-muted uppercase tracking-widest mb-3">History</p>
            {payslips.map(p => (
              <button key={p.id} onClick={() => setSelected(p)}
                className={`w-full flex items-center gap-3 p-4 rounded-xl border text-left transition-all duration-300 ${
                  selected?.id===p.id ? 'border-accent/30 bg-accent/10' : 'border-border bg-surface hover:border-accent/20'}`}>
                <div className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: selected?.id===p.id ? 'rgba(79,142,247,0.2)' : 'rgba(255,255,255,0.05)' }}>
                  <DollarSign size={16} className={selected?.id===p.id ? 'text-accent' : 'text-muted'}/>
                </div>
                <div className="flex-1">
                  <p className="font-display font-semibold text-sm text-bright">{MONTHS[p.month-1]} {p.year}</p>
                  <p className="font-mono text-xs text-accent">₹{p.netSalary?.toLocaleString()}</p>
                </div>
                <div className="flex flex-col items-end gap-1">
                  <span className="badge-blue text-xs">{p.status}</span>
                  {p.attendanceDeduction > 0 && (
                    <span className="text-xs font-mono text-red-400">-5% att.</span>
                  )}
                </div>
              </button>
            ))}
          </div>

          {/* Detail */}
          {selected && (
            <div className="col-span-2 stat-card">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <p className="text-xs font-mono text-muted uppercase tracking-widest mb-1">Pay Slip</p>
                  <h3 className="font-display font-bold text-xl text-bright">{MONTHS[selected.month-1]} {selected.year}</h3>
                </div>
                <span className="badge-blue">{selected.status}</span>
              </div>

              {/* Attendance status banner */}
              {selected.attendancePercentage !== null && selected.attendancePercentage !== undefined && (
                <div className={`flex items-center gap-3 px-4 py-3 rounded-xl border mb-5 ${
                  selected.attendanceDeduction > 0
                    ? 'bg-red-500/8 border-red-500/20'
                    : 'bg-accent-3/8 border-accent-3/20'}`}>
                  {selected.attendanceDeduction > 0
                    ? <AlertTriangle size={16} className="text-red-400 flex-shrink-0"/>
                    : <CheckCircle size={16} className="text-accent-3 flex-shrink-0"/>}
                  <div>
                    <p className={`text-sm font-body font-semibold ${selected.attendanceDeduction > 0 ? 'text-red-400' : 'text-accent-3'}`}>
                      Attendance: {selected.attendancePercentage}%
                    </p>
                    <p className="text-xs font-mono text-muted">{selected.attendanceNote}</p>
                  </div>
                </div>
              )}

              {/* Earnings */}
              <div className="mb-4">
                <p className="text-xs font-mono text-accent-3 uppercase tracking-widest mb-3 flex items-center gap-2">
                  <TrendingUp size={12}/> Earnings
                </p>
                <div className="space-y-2">
                  {[['Basic Salary', selected.basicSalary], ['HRA (20%)', selected.hra], ['Bonus', selected.bonus]].map(([l, v]) => v > 0 && (
                    <div key={l} className="flex items-center justify-between p-3 rounded-xl bg-accent-3/5 border border-accent-3/10">
                      <span className="text-sm font-body text-dim">{l}</span>
                      <span className="text-sm font-mono text-accent-3">+₹{v?.toLocaleString()}</span>
                    </div>
                  ))}
                  <div className="flex items-center justify-between p-3 rounded-xl bg-surface border border-border/50">
                    <span className="text-sm font-body font-medium text-bright">Gross Total</span>
                    <span className="text-sm font-mono font-bold text-bright">
                      ₹{((selected.basicSalary||0)+(selected.hra||0)+(selected.bonus||0)).toLocaleString()}
                    </span>
                  </div>
                </div>
              </div>

              {/* Deductions */}
              <div className="mb-6">
                <p className="text-xs font-mono text-red-400 uppercase tracking-widest mb-3 flex items-center gap-2">
                  <TrendingDown size={12}/> Deductions
                </p>
                <div className="space-y-2">
                  {[['PF (12%)', selected.pfDeduction], ['Tax (10%)', selected.taxDeduction]].map(([l, v]) => (
                    <div key={l} className="flex items-center justify-between p-3 rounded-xl bg-red-500/5 border border-red-500/10">
                      <span className="text-sm font-body text-dim">{l}</span>
                      <span className="text-sm font-mono text-red-400">-₹{v?.toLocaleString()}</span>
                    </div>
                  ))}
                  {selected.attendanceDeduction > 0 && (
                    <div className="flex items-center justify-between p-3 rounded-xl bg-red-500/10 border border-red-500/20">
                      <div>
                        <span className="text-sm font-body text-red-400 font-semibold">Attendance Deduction (5%)</span>
                        <p className="text-xs font-mono text-muted">{selected.attendancePercentage}% attendance — below 75% threshold</p>
                      </div>
                      <span className="text-sm font-mono text-red-400 font-bold">-₹{selected.attendanceDeduction?.toLocaleString()}</span>
                    </div>
                  )}
                </div>
              </div>

              {/* Net */}
              <div className="p-5 rounded-2xl flex items-center justify-between"
                style={{ background: 'linear-gradient(135deg, rgba(79,142,247,0.1), rgba(124,58,237,0.08))', border: '1px solid rgba(79,142,247,0.2)' }}>
                <div>
                  <p className="text-xs font-mono text-accent uppercase tracking-widest mb-1">Net Salary</p>
                  <p className="text-3xl font-display font-bold text-bright">₹{selected.netSalary?.toLocaleString()}</p>
                </div>
                <div className="text-right text-xs font-mono text-muted">
                  <p>Generated: {selected.generatedOn}</p>
                  <p className="mt-1 text-accent">{selected.status}</p>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
